
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kechita-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kechita
  template:
    metadata:
      labels:
        app: kechita
    spec:
      containers:
        - name: kechita
          image: kechita/app:latest
          ports:
            - containerPort: 3000
